version: '3.8'
services:
  db:
    container_name: mysql-bedu
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
